# Generated by Django 5.1.7 on 2025-04-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'db_table': 'platforms',
            },
        ),
        migrations.CreateModel(
            name='FavGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Nombre')),
                ('rating_score', models.FloatField(default=0, verbose_name='Nota')),
                ('release_year', models.IntegerField(default=0, verbose_name='Año lanzamiento')),
                ('image_url', models.URLField(default='', verbose_name='URL de imagen')),
                ('genres', models.ManyToManyField(related_name='favgames', to='favgames.genre', verbose_name='Genres')),
                ('platforms', models.ManyToManyField(related_name='favgames', to='favgames.platform', verbose_name='Platformas')),
            ],
            options={
                'verbose_name': 'Juego favorito',
                'verbose_name_plural': 'Juegos favoritos',
                'db_table': 'favgames',
            },
        ),
    ]
