# Generated by Django 5.1.7 on 2025-04-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favgames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favgame',
            name='genres',
            field=models.ManyToManyField(blank=True, default=[], related_name='favgames', to='favgames.genre', verbose_name='Genres'),
        ),
        migrations.AlterField(
            model_name='favgame',
            name='image_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='URL de imagen'),
        ),
        migrations.AlterField(
            model_name='favgame',
            name='platforms',
            field=models.ManyToManyField(blank=True, default=[], related_name='favgames', to='favgames.platform', verbose_name='Platformas'),
        ),
        migrations.AlterField(
            model_name='favgame',
            name='rating_score',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='favgame',
            name='release_year',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Año lanzamiento'),
        ),
    ]
