# Generated by Django 5.1.7 on 2025-05-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favgames', '0002_alter_favgame_genres_alter_favgame_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favgame',
            name='id_api',
            field=models.IntegerField(default=0, verbose_name='ID API'),
        ),
    ]
