# Generated by Django 5.2.5 on 2025-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favgames', '0003_favgame_id_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favgame',
            name='name',
            field=models.CharField(verbose_name='Nombre'),
        ),
    ]
