# Generated by Django 5.2.5 on 2025-11-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favgames', '0004_alter_favgame_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favgame',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.RemoveField(
            model_name='favgame',
            name='release_year',
        ),
        migrations.AddField(
            model_name='favgame',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date'),
        ),
        migrations.AddField(
            model_name='favgame',
            name='summary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='favgame',
            name='image_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='favgame',
            name='name',
            field=models.CharField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='favgame',
            name='platforms',
            field=models.ManyToManyField(blank=True, default=[], related_name='favgames', to='favgames.platform', verbose_name='Platforms'),
        ),
        migrations.AlterField(
            model_name='favgame',
            name='rating_score',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Rating'),
        ),
    ]
