# Generated by Django 5.2.5 on 2025-11-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favgames', '0005_alter_favgame_options_remove_favgame_release_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Platform', 'verbose_name_plural': 'Platforms'},
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(unique=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='abbreviation',
            field=models.CharField(unique=True, verbose_name='abbreviation'),
        ),
    ]
