# Generated by Django 5.2.5 on 2025-11-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favgames', '0006_alter_genre_options_alter_platform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='name',
            field=models.CharField(default='', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='abbreviation',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='abbreviation'),
        ),
    ]
