# Generated by Django 5.1.7 on 2025-05-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favgames', '0003_favgame_id_api'),
        ('users', '0005_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='played_games',
            field=models.ManyToManyField(blank=True, related_name='played_by', to='favgames.favgame'),
        ),
    ]
