# Generated by Django 5.2.5 on 2025-11-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_options_customuser_is_subscribed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
