# Generated by Django 5.2.5 on 2025-11-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='googleId',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Google ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, verbose_name='Username'),
        ),
    ]
