# Generated by Django 5.2.5 on 2025-11-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_googleid_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='googleId',
            new_name='google_id',
        ),
    ]
