# Generated by Django 5.2.5 on 2025-11-27 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_googleid_customuser_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Slug'),
        ),
    ]
